### PR TITLE
encode product name, cloud id and issuer in QR code for disambiguation

### PR DESCRIPTION
**Pull request by ChristophWurst**
fixes https://github.com/ChristophWurst/twofactor_totp/issues/3.

It now takes the cloud id (e.g. `christoph@my.cloud.com`) as label and the instance url + product name as issuer (e.g. `https://my.cloud.com (Nextcloud)`).

This replaces #18 

@danimo @jas4711 @mar1u5 please test/review

### CODE REVIEW

**Comment by mar1u5** [comment]
Great work 👍 ... I would like to hear @LukasReschke about how we want to go on with this (shipping, position within Nextcloud, ...)

**Comment by ChristophWurst** [comment]
> I would like to hear @LukasReschke about how we want to go on with this (shipping, position within Nextcloud, ...)

I plan to publish this app on apps.nextcloud.com soon ;-)

**Comment by mar1u5** [comment]
yay 🎆 ...but I think we should have it for 10 😉 Pluggable Auth does not seem to have any advantages without any twofactor provider 😜

**Comment by ChristophWurst** [comment]
> Pluggable Auth does not seem to have any advantages without any twofactor provider

It does: app passwords and managing connected browsers ;-)

**Comment by mar1u5** [comment]
> It does: app passwords and managing connected browsers ;-)

😏

**Comment by jas4711** [comment]
Thanks -- but how do I test this?  I tried to git clone the repository and replace the directory from apps.owncloud.org with the git repo, but then some files are missing (I get an error regarding Otp\\Otp class) such as the vendor/ sub-directory.  There is no makefile in the git repo either to generate files, which exists in some other apps.  Thanks.

**Comment by ChristophWurst** [comment]
> There is no makefile in the git repo either to generate files

Really? https://github.com/ChristophWurst/twofactor_totp/blob/master/Makefile ;-)

I've published a new version of this app already, which you can install via the app store or the release page on GitHub https://github.com/ChristophWurst/twofactor_totp/releases

**Pull request merged**
